import { defineConfig, Plugin } from 'vite';
import tailwindcss from '@tailwindcss/vite';
import fs from 'fs';
import path from 'path';

export default defineConfig({
	plugins: [tailwindcss(), tailwindAtProperties()],
});

function tailwindAtProperties(): Plugin {
	return {
		name: 'tailwindAtProperties',
		transform(code, id) {
			if (!id.includes('tailwind-styles-root.css')) {
				return;
			}

			const propertyRegex = /@property\s+[^{]+\{[^}]+\}/gs;
			const matches = code.match(propertyRegex);

			const s = '/* Autogenerated by tailwindAtProperties plugin (see vite.config.ts) */\n';
			fs.writeFileSync(
				path.resolve(import.meta.dirname, 'src/tailwind/at-properties.css'),
				matches === null ? s : s + matches.join('\n')
			);
		},
	};
}
